name: Node.js CI

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Eslint
        run: |
          npm ci
          npm install eslint
      - run: npm run build --if-present
      - name: Eslint working flow
        run: |
          npm run eslint:check
          npm run stylelint:check